FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG API_BASE_URL=/api
RUN sed -i "s|\${API_BASE_URL}|${API_BASE_URL}|g" src/environments/environment.ts \
  && npm run build

FROM nginx:1.27-alpine AS final
WORKDIR /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/contratos/browser ./

EXPOSE 80
