FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG API_BASE_URL=/api
RUN sed -i "s|\${API_BASE_URL}|${API_BASE_URL}|g" src/environments/environment.ts \
  && npm run build

FROM nginx:1.29.5-alpine AS final
WORKDIR /usr/share/nginx/html

ENV BASE_HREF=/

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint.d/40-configure-base-href.sh /docker-entrypoint.d/40-configure-base-href.sh
COPY --from=build /app/dist/inventario/browser ./

EXPOSE 80
